"""empty message

Revision ID: 3239cf7bd1a4
Revises: f4fd0b2945f8
Create Date: 2025-09-10 14:31:47.708176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3239cf7bd1a4'
down_revision = 'f4fd0b2945f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('references')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('references', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
