"""Add document_url to Lesson

Revision ID: 9cc3d8fb4401
Revises: 3239cf7bd1a4
Create Date: 2025-09-16 13:23:44.040555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc3d8fb4401'
down_revision = '3239cf7bd1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('document_url')

    # ### end Alembic commands ###
