"""empty message

Revision ID: d55f1c1cb4bb
Revises: d77a06276631
Create Date: 2025-09-26 15:19:25.975356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd55f1c1cb4bb'
down_revision = 'd77a06276631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('subcategories')
    op.drop_table('resource')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.drop_constraint(batch_op.f('lesson_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lesson_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])
        batch_op.drop_column('course_id')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_ibfk_2'), 'subcategories', ['subcategory_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('lesson_ibfk_1'), 'course', ['course_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('section_id')
        batch_op.drop_column('size')
        batch_op.drop_column('duration')
        batch_op.drop_column('slug')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image')
        batch_op.drop_column('slug')
        batch_op.drop_column('long_description')

    op.create_table('resource',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('resource_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('subcategories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('subcategories_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('sections')
    op.drop_table('resources')
    # ### end Alembic commands ###
